build site:
  image: node:10
  stage: build
  script:
    - echo "NODE VERSION" && node --version
    - echo "NPM VERSION" && npm --version
    - echo "YARN VERSION" && yarn --version
    - yarn
    - yarn build
  artifacts:
    expire_in: 1 week
    paths:
      - build

tests:
  image: node:10
  stage: test
  script:
    - yarn
    - yarn test

deploy:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete build/ user@server.com:/your/project/path/